//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Policlinica.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adresa
    {
        public int Fk_UnitateMedicalaId { get; set; }
        public string Numar { get; set; }
        public string Judet { get; set; }
        public string Localitate { get; set; }
        public string Adresa1 { get; set; }
    
        public virtual UnitateMedicala UnitateMedicala { get; set; }
    }
}
