//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Policlinica.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsistentMedical
    {
        public int Fk_UtilizatorId { get; set; }
        public int Grad { get; set; }
        public int Tip { get; set; }
    
        public virtual Utilizatori Utilizatori { get; set; }
    }
}
