//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Policlinica.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medic()
        {
            this.ProceduriMedic = new HashSet<ProceduriMedic>();
            this.ServiciiMedicale = new HashSet<ServiciiMedicale>();
            this.Specialitati = new HashSet<Specialitati>();
        }
    
        public int Fk_UtilizatorId { get; set; }
        public int Grad { get; set; }
        public string CodulDeParafa { get; set; }
        public Nullable<int> TitlulStiintific { get; set; }
        public Nullable<int> PostulDidactic { get; set; }
        public Nullable<decimal> ProcentServicii { get; set; }
    
        public virtual Utilizatori Utilizatori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProceduriMedic> ProceduriMedic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiciiMedicale> ServiciiMedicale { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Specialitati> Specialitati { get; set; }
    }
}
