//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Policlinica.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrarUnitateMedicala
    {
        public int OrarId { get; set; }
        public int Zi { get; set; }
        public System.TimeSpan OraDeschidere { get; set; }
        public System.TimeSpan OraInchidere { get; set; }
        public int Fk_UnitateMedicalaId { get; set; }
    
        public virtual UnitateMedicala UnitateMedicala { get; set; }
    }
}
