//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Policlinica.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrarUtilizatori
    {
        public int OrarId { get; set; }
        public int Zi { get; set; }
        public System.TimeSpan SfarsitProgram { get; set; }
        public Nullable<System.DateTime> DataZiSpeciala { get; set; }
        public int Fk_UtilizatorId { get; set; }
        public System.TimeSpan IncepereProgram { get; set; }
    
        public virtual Utilizatori Utilizatori { get; set; }
    }
}
