//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Policlinica.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramariServicii
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProgramariServicii()
        {
            this.BonuriFiscale = new HashSet<BonuriFiscale>();
            this.ServiciiMedicale = new HashSet<ServiciiMedicale>();
        }
    
        public int ProgramareId { get; set; }
        public int Fk_PacientId { get; set; }
        public int Fk_ReceptionerId { get; set; }
        public System.DateTime DataProgramare { get; set; }
        public Nullable<bool> Realizata { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BonuriFiscale> BonuriFiscale { get; set; }
        public virtual Pacient Pacient { get; set; }
        public virtual Utilizatori Utilizatori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiciiMedicale> ServiciiMedicale { get; set; }
    }
}
