//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Policlinica.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RaportMedical
    {
        public int Fk_ServiciuMedicalId { get; set; }
        public string NumePrenumeMedic { get; set; }
        public string NumePrenumePacient { get; set; }
        public Nullable<System.DateTime> DataConsultatie { get; set; }
        public string Istoric { get; set; }
        public string Simptome { get; set; }
        public string Investigații { get; set; }
        public string Diagnostic { get; set; }
        public string Recomandări { get; set; }
        public int Status { get; set; }
    
        public virtual ServiciiMedicale ServiciiMedicale { get; set; }
    }
}
