//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Policlinica.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiciiMedicale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiciiMedicale()
        {
            this.Specialitati = new HashSet<Specialitati>();
        }
    
        public int ServiciuMedicalId { get; set; }
        public string Competenta { get; set; }
        public Nullable<decimal> Pret { get; set; }
        public int Durata { get; set; }
        public int Fk_UnitateMedicala { get; set; }
        public Nullable<int> Fk_MedicId { get; set; }
        public int Fk_ProgramareId { get; set; }
    
        public virtual Medic Medic { get; set; }
        public virtual ProgramariServicii ProgramariServicii { get; set; }
        public virtual RaportMedical RaportMedical { get; set; }
        public virtual UnitateMedicala UnitateMedicala { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Specialitati> Specialitati { get; set; }
    }
}
